services:
  # vue:
  #   network_mode:  host
  #   container_name: "vue"
  #   image: node:cem
  #   build:
  #     context: .
  #     tags:
  #       - node:cem
  #   restart: on-failure:3
  #   working_dir: "$PWD/vue"
  #   entrypoint: ["npx", "vite", "--host"]
  #   volumes:
  #     - "node_modules:${PWD}/node_modules"
  #     - "${PWD}/vue:${PWD}/vue"
  #     - "${PWD}/package.json:${PWD}/package.json"
  #     - "${PWD}/tsconfig.json:${PWD}/tsconfig.json"

  worker:
    network_mode:  host
    container_name: "worker"
    image: node:cem
    build:
      context: .
      tags:
        - node:cem
    restart: on-failure:3
    tty: true
    stdin_open: true
    working_dir: "$PWD"
    entrypoint: ["npx", "wrangler", "dev"]
    volumes:
      - "${PWD}/.config:/root/.config"
      - "${PWD}/db:${PWD}/db"
      - "${PWD}/vue/dist:${PWD}/vue/dist"
      - "${PWD}/scripts:${PWD}/scripts"
      - "node_modules:${PWD}/node_modules"
      - "${PWD}/worker:${PWD}/worker"
      - "${PWD}/wrangler.toml:${PWD}/wrangler.toml"
      - "${PWD}/package.json:${PWD}/package.json"
      - "${PWD}/tsconfig.json:${PWD}/tsconfig.json"

volumes:
  node_modules:
    name: node_modules
