# Cloudflare Workers 配置文件
# 邮箱管理系统 (CEM - Cloudflare Email Manager)

name = "cem"
compatibility_date = "2025-09-10"
main = "worker/src/main.ts"
compatibility_flags = ["nodejs_compat"]

# ----- 全局配置 -----

# 本地开发服务器配置
[dev]
ip = "0.0.0.0"
port = 8787

# 定时任务
[triggers]
crons = ["0 2 * * *"]                 # 每天凌晨2点执行清理

# 可观测性
[observability]
enabled = true
head_sampling_rate = 1

# 静态资源绑定 - 前端构建产物
[assets]
directory = "vue/dist/"
binding = "ASSETS"
run_worker_first = true

# ----- 生产环境-----
  # D1 数据库
  [[d1_databases]]
  binding = "DB"
  database_id = ""                      # 部署脚本会自动填充
  database_name = "cem-db"
  remote = true # 当你想直接使用 生产环境数据的时候需要启用 TODO 完善

  # R2 存储桶
  [[r2_buckets]]
  binding = "R2"
  bucket_name = "cem-r2"

  # KV 存储
  [[kv_namespaces]]
  binding = "KV"
  id = ""                               # 部署脚本会自动填充

# ----- 开发环境-----
# 开发环境配置 (云端部署)
[env.dev]
name = "cem-dev"

  # D1 数据库
  [[env.dev.d1_databases]]
  binding = "DB"
  database_name = "cem-db-dev"
  database_id = ""                            # 部署脚本会自动填充

  # R2 存储桶
  [[env.dev.r2_buckets]]
  binding = "R2"
  bucket_name = "cem-r2-dev"

  # KV 存储
  [[env.dev.kv_namespaces]]
  binding = "KV"
  id = ""                                     # 部署脚本会自动填充