#:schema node_modules/wrangler/config-schema.json
name = "email-sender"
main = "src/index.ts"
compatibility_date = "2024-04-05"

dev.host = "127.0.0.1"
dev.port = 8787

[vars]
# 自定义域名的发信邮件地址
# SENDER_EMAIL = "do-not-replay@example.com"
# 发信人简称/名字
# SENDER_NAME = "Example"

[[d1_databases]]
# D1 数据库绑定名称与数据库 ID 需在部署前于 Cloudflare 控制台创建
binding = "DB"
database_name = "email_db"
database_id = "__REPLACE_WITH_D1_ID__"

[[r2_buckets]]
# R2 存储桶绑定，用于保存邮件附件
binding = "R2"
bucket_name = "email-attachments"
