/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoadingSpinner: typeof import('./src/components/UI/AppLoadingSpinner.vue')['default']
    AuthExample: typeof import('./src/components/AuthExample.vue')['default']
    EmailDetail: typeof import('./src/components/Email/EmailDetail.vue')['default']
    EmailList: typeof import('./src/components/Email/EmailList.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    LoadingExamples: typeof import('./src/components/UI/LoadingExamples.vue')['default']
    LoadingOverlay: typeof import('./src/components/UI/LoadingOverlay.vue')['default']
    MailboxList: typeof import('./src/components/Mailbox/MailboxList.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SecurityWidget: typeof import('./src/components/SecurityWidget.vue')['default']
    Sidebar: typeof import('./src/components/Layout/Sidebar.vue')['default']
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default']
    TopBar: typeof import('./src/components/Layout/TopBar.vue')['default']
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default']
  }
}
