/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppLoadingSpinner: typeof import('./src/components/shared/AppLoadingSpinner.vue')['default']
    Button: typeof import('./src/components/common/Button.vue')['default']
    CheckboxField: typeof import('./src/components/common/CheckboxField.vue')['default']
    DataTable: typeof import('./src/components/shared/DataTable.vue')['default']
    DomainListInput: typeof import('./src/components/common/DomainListInput.vue')['default']
    EmailDetailModal: typeof import('./src/components/business/EmailDetailModal.vue')['default']
    EmailList: typeof import('./src/components/business/EmailList.vue')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    LoginCard: typeof import('./src/components/auth/LoginCard.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PageStates: typeof import('./src/components/common/PageStates.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBox: typeof import('./src/components/shared/SearchBox.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
    TagListInput: typeof import('./src/components/common/TagListInput.vue')['default']
    WebhookConfigFields: typeof import('./src/components/business/WebhookConfigFields.vue')['default']
  }
}
