/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/common/Button.vue')['default']
    CheckboxField: typeof import('./src/components/common/CheckboxField.vue')['default']
    DebugInfo: typeof import('./src/components/common/DebugInfo.vue')['default']
    DomainListInput: typeof import('./src/components/common/DomainListInput.vue')['default']
    EmailList: typeof import('./src/components/business/EmailList.vue')['default']
    FormField: typeof import('./src/components/common/FormField.vue')['default']
    MailboxList: typeof import('./src/components/business/MailboxList.vue')['default']
    Modal: typeof import('./src/components/common/Modal.vue')['default']
    PageHeader: typeof import('./src/components/common/PageHeader.vue')['default']
    PageStates: typeof import('./src/components/common/PageStates.vue')['default']
    Pagination: typeof import('./src/components/common/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsForm: typeof import('./src/components/business/SettingsForm.vue')['default']
    StatusBadge: typeof import('./src/components/common/StatusBadge.vue')['default']
  }
}
